KidPortfolio/KidPortfolio/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib.auth import views

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', views.login,name='login'),
    url(r'^accounts/logout/$', views.logout,name='logout',kwargs={'next_page': '/'}),
    url(r'',include('kidfolio.urls')),
    url(r'^front-edit/',include('front.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

KidPortfolio/kidfolio/urls.py
from django.conf.urls import url
from kidfolio import views

app_name = 'kidfolio'
urlpatterns = [
    #url(r'^$', views.index, name="index"),
    url(r'^$', views.index, name="index"),
    url(r'^get_portfolios/$', views.get_portfolios, name="get_portfolios"),
    url(r'^new_kidpost/$', views.new_kidpost, name="new_kidpost"),
    url(r'^new_portfolio/$', views.new_portfolio, name="new_portfolio"),
    url(r'^publish_new_kidpost/$', views.publish_new_kidpost, name="publish_new_kidpost"),
    url(r'^create_portfolio/$', views.create_portfolio, name="create_portfolio"),
    # url(r'^edit_kidpost/(?P<kid_id>[0-9]+)$', views.edit_kidpost, name='edit_kidpost'),
    url(r'^get_kidpost/(?P<kid_id>[0-9]+)$', views.get_kidpost, name='get_kidpost'),
    url(r'^new_user/$', views.new_user, name='new_user'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^get_thumbnail_view/$', views.get_thumbnail_view, name='get_thumbnail_view'),
    url(r'^get_this_portfolio/(?P<portfolio_id>[0-9]+)$', views.get_this_portfolio, name='get_this_portfolio'),

]

KidPortfolio/kidfolio/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage
from django.utils import timezone
from django.contrib.auth.models import User

class Category(models.Model):
    category = models.CharField(max_length=34)

    def __str__(self):
        return self.category

class Portfolio(models.Model):
    # images = models.
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    portfolio_name = models.CharField(max_length=34)
    def __str__(self):
        return self.portfolio_name

class KidPicPost(models.Model):

    image = models.ImageField(upload_to='images/', width_field="width_field", height_field="height_field",)
    height_field = models.IntegerField(default=400)
    width_field = models.IntegerField(default=400)
    create_date = models.DateTimeField(default=timezone.now,auto_created=True)
    title = models.CharField(max_length=34,blank=True)
    caption = models.TextField(max_length=500,blank=True)
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE)
    category = models.ForeignKey(Category,blank=True,null=True)

    def publish(self):

        self.pub_date = timezone.now()
        self.save()


    def __str__(self):
        return self.title


    # def remove_pic(self):
    #     self.image = delete()
    #     self.save()
    #
    #

KidPortfolio/kidfolio/forms.py
from django.forms import ModelForm
from .models import KidPicPost,Portfolio
from django import forms

# class KidpicpostForm(forms.ModelForm):
#     class Meta:
#         model = KidPicPost
#         fields = ['image', 'title', 'caption', 'portfolio','category']

class KidPicForm(forms.ModelForm):
    class Meta:
        model = KidPicPost
        fields = ['image', 'title', 'caption', 'portfolio', 'category']

        widgets = {
            # 'title':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'}),
            # 'caption':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
        }




class PortfolioForm(forms.ModelForm):
    class Meta:
        model = Portfolio
        fields = ['portfolio_name', 'author']

        widgets = {
            # 'portfolio_name':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'}),
            'author': forms.HiddenInput()
        }

#need to figure out this widget, has a problem with the forms. says its undefined. perhaps need to import it. not sure from where.

KidPortfolio/kidfolio/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from kidfolio.models import KidPicPost,Portfolio,Category
from .forms import KidPicForm, PortfolioForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout


def index(request):
    return render(request, 'kidfolio/about.html')

# def receive_kidpost(request):
#     my_image = request.FILES['my_image']
#     model = KidPicPost(..., my_image=my_image)
#     KidPicPost.save()


def new_kidpost(request):
    form = KidPicForm(initial={'author': request.user})
    return render(request, 'kidfolio/new_kidpost.html', {'form':form})


def publish_new_kidpost(request):
    form = KidPicForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('kidfolio:get_portfolios'))
    else:
        return HttpResponseRedirect(reverse('kidfolio:new_kidpost'))


def new_portfolio(request):
    form = PortfolioForm(initial={'author': request.user})
    return render(request, 'kidfolio/new_portfolio.html', {'form':form})


def create_portfolio(request):
    if request.method == "POST":
        form = PortfolioForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('kidfolio:get_portfolios'))
        else:
            return HttpResponseRedirect(reverse('kidfolio:new_portfolio'))


def get_kidpost(request, kid_id):
    # return HttpResponse('you are at the detail_view.html') #this url works
    post = get_object_or_404(KidPicPost, pk=kid_id)
    if request.method == 'POST':
        post.title = request.POST['title']
        post.save()
        post.caption = request.POST['caption']
        post.save()
    return render(request, 'kidfolio/detail_view.html', {'post': post})


def new_user(request):
    if request.method == 'POST':
        user = User.objects.create_user(request.POST['username'], request.POST['email'], request.POST['password'])
        login(request, user)
        return HttpResponseRedirect(reverse('kidfolio:get_portfolios'))

def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('kidfolio:get_portfolios'))
        else:
            pass
            return HttpResponseRedirect(reverse('kidfolio:index'))

def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('kidfolio:index'))

def get_portfolios(request):
    # user = request.user
    #portfolios = user.portfolio_set.all()
    #return render(request, 'kidfolio/portfolios.html', {'portfolios': portfolios})
    return render(request, 'kidfolio/portfolios.html')

def get_this_portfolio(request, portfolio_id):
    portfolio = get_object_or_404(Portfolio, pk=portfolio_id)
    return render(request, 'kidfolio/portfolio_detail.html', {'portfolio': portfolio})

def get_thumbnail_view(request):

    return render(request, 'kidfolio/thumbnail.html')

KidPortfolio/kidfolio/templates/kidfolio/about.html
{% extends "kidfolio/base.html" %}
{% block content%}
<div class="about">
    <div class="jumbotron container">
        <div class="message">
            <h1>Welcome!</h1>
            <h2>New users please fill out Registration</h2>
            <h2>Current users login with username and password</h2>
        </div>




    </div>
</div>

<script>
    // Want to see your own message appear?
// Just change the message value!
const message = `Welcome to KidFolio.
This is tool to help you declutter.
Register as a new user.
Login as a current user.`;


// Want to use this in your own code? Just copy and paste everything here, but change the value of the "container" variable (currently '#target') to match your chosen target DOM element.
// Also be sure the target element has the right white-space CSS in your code.
const container = document.querySelector('#target');

let n;

function rerun(){
	container.textContent = '';
	n = 0;
	typist(message, container);
};

rerun();

function interval(letter){
	console.log(letter);
	if(letter == ';' || letter == '.' || letter == ','){
		return Math.floor((Math.random() * 500) + 500);
	} else {
		return Math.floor((Math.random() * 130) + 5);
	}
}

function typist(text, target){
	if(typeof(text[n]) != 'undefined'){
		target.textContent += text[n];
	}
	n++;
	if(n < text.length){
		setTimeout(function(){
			typist(text, target)
		}, interval(text[n - 1]));
	}
}

</script>


{% endblock%}

KidPortfolio/kidfolio/templates/kidfolio/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>KidFolio</title>
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href='{% static "css/kidstyle.css" %}'/>
        <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
        <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">
    </head>
    <body>


            <nav class="navbar navbar-default techfont custom-navbar">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand bigbrand" href="{% url 'kidfolio:index' %}">KidFolio</a></li>


                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'kidfolio:get_portfolios' %}">Your Portfolios</a>
                    </li>

                    <li>
                        <a href="{% url 'kidfolio:new_kidpost' %}">New Kidpost</a>
                    </li>
                    <li>
                        <a href="{% url 'kidfolio:new_portfolio' %}">New Portfolio</a>
                    </li>
                    <li>
                        <a>Welcome: {{ user.username }}</a>
                    </li>
                    <li>
                        <a href="{% url 'kidfolio:user_logout' %}">Logout</a>
                    </li>
                    {% else %}
                        <li>
                            <a class='nav navbar-right' href="{% url 'login' %}"><span class="glyphicon glyphicon-user"></span></a>

                        </li>
                    {% endif%}
                </ul>



        </nav>

        <div class="container main-content">

               {% block content %}
               {% endblock%}
        </div>




    </body>
</html>

KidPortfolio/kidfolio/templates/kidfolio/detail_view.html
{% extends "kidfolio/base.html" %}
{% block content%}


    <div class="detail_view w3-center">
        <form action="" method="post">
            {% csrf_token %}
            <h3>
                <input type="text" class="title-text" name="title"
                       value="{{post.title}}" />
            </h3>
                <img class="detail_pic pic" src="{{ post.image.url }}" alt="Card image cap">


            <p>
                <input type="text" class="caption-text" name="caption"
                    value = "{{post.caption}}" />

            </p>

            <button type="submit" class="save btn btn-default">save</button>
        </form>
    </div>




{% endblock %}

KidPortfolio/kidfolio/templates/kidfolio/edit_page.html
{% extends "kidfolio/base.html" %}
{% block content%}

        <div class="kidpic_container">
            <h2>{{ form.title }} by {{ form.portfolio }}</h2>
            <div class="art_container">

                    <img class="edit_btn" src="{{ kidpost.image.url }}"/>

            </div>
            <p class="caption">{{ post.caption }}</p>
        </div>


{% endblock %}

KidPortfolio/kidfolio/templates/kidfolio/example.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>KidFolio Portfolio Page</title>
        <meta name="description" content="">
        <link rel="stylesheet" type="text/css" href='{% static "css/kidstyle.css" %}'/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>

    <body>
        <h1>Welcome!</h1>
        <h2>Here are your Portfolio's</h2>
        <a href="{% url 'kidfolio:new_kidpost' %}">
            <button class="make_entry">New KidPost</button>
        </a>
       <div>
           {% for portfolio in user.portfolio_set.all %}
           <h1>{{portfolio.portfolio_name}}</h1>

            <h3>{{ portfolio.kidpicpost_set.first}}</h3>
            <div>
                {% with first_post=portfolio.kidpicpost_set.first %}
                {% if first_post %}
                <div class="art_container">
                    <a href="{% url 'kidfolio:get_kidpost' first_post.id %}">
                        <img class="edit_btn" src="{{ first_post.image.url }}"/>
                    </a>
                </div>

                {% for post in portfolio.kidpicpost_set.all %}
                <h3>{{post.title}}</h3>
                {% endfor %}


                {% endif %}
                {% endwith %}
            </div>
            {% endfor %}
        </ul>


       </div>

    </body>

<!--portfolio_detail page old info-->
<div class="card" style="width: 40em;">
        <div class="card-header">
            <h3 class="cap_title">{% autoescape off %} {{post.title}} {% endautoescape %}</h3>
        </div>
        <a href="{% url 'kidfolio:get_kidpost' post.id %}">
            <img class="card-img-top portfolio_detail_pic pic" src="{{ post.image.url }}" alt="Card image cap">
        </a>
        <div class="card-body">

          <p class="card-text">{% autoescape off %} {{post.caption}} {% endautoescape %}</p>
        </div>
    </div>

KidPortfolio/kidfolio/templates/kidfolio/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>KidFolio Portfolio Page</title>
        <meta name="description" content="">
        <link rel="stylesheet" type="text/css" href='{% static "css/kidstyle.css" %}'/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <h1>Hi welcome!</h1>
        <h2>Here are your Kid Pics</h2>
        <a href="{% url 'kidfolio:new_kidpost' %}">
            <button class="make_entry">New KidPost</button>
        </a>


        {% for post in kidpost %}
        <div class="kidpic_container">
            <h2>{{ post.title }} by {{ post.portfolio }}</h2>
            <div class="art_container">
                <img src="{{ post.image.url }}"/>
            </div>
            <p class="caption">{{ post.caption }}</p>
        </div>
        {% endfor %}


    </body>
</html>

KidPortfolio/kidfolio/templates/kidfolio/landing_page.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Sign In</title>
        <meta name="description" content="">
        <link rel="stylesheet" type="text/css" href="style.css">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>


    </body>
</html>

KidPortfolio/kidfolio/templates/kidfolio/new_kidpost.html
{% extends 'kidfolio/base.html' %}
{% block content%}

<div class="container">
    <div class="jumbotron">
    <form class="post-form" action="{% url 'kidfolio:publish_new_kidpost' %}" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <div class="title">
                <h3>Art Title:</h3>
                {{ form.title }}
            </div>

            <div class="image">
                <h3>Upload Image: </h3>
                {{ form.image }}
            </div>

            <div class="caption">
                <h3>Creation Notes: </h3>
                {{ form.caption }}
            </div>

            <div class="portfolio">
                <h3>Which Portfolio?:</h3>
                {{ form.portfolio }}
            </div>

            <div class="category">
                <h3>Category: </h3>
                {{ form.category }}
            </div>



            <button type="submit" class="save btn btn-default">Add</button>

        </form>


</div>

</div>

<script>
    var editor = new MediumEditor('.editable');
</script>



{% endblock %}

KidPortfolio/kidfolio/templates/kidfolio/new_portfolio.html
{% extends "kidfolio/base.html" %}
{% block content%}
<div class="jumbotron w3-center">
    <form action="{% url 'kidfolio:create_portfolio' %}"  method="post">
        {% csrf_token %}
            <div class="title">
                <h3>Add New Portfolio</h3>
                {{ form.portfolio_name }}
                {{ form.author }}
            </div>

            <button type="submit">Add</button>
    </form>


</div>



{% endblock %}

KidPortfolio/kidfolio/templates/kidfolio/portfolio_detail.html
{% extends "kidfolio/base.html" %}
{% block content %}
<!--<div>-->
    <!--<button class="w3-button">Thumbnail</button>-->
<!--</div>-->

<div class="container slideshow">
    <h1 class="w3-center">{{portfolio.portfolio_name}}</h1>
    <button class="w3-button w3-white w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
    <button class="w3-button w3-white w3-display-right" onclick="plusDivs(1)">&#10095;</button>

    <div class="w3-content w3-display-container">

    {% for post in portfolio.kidpicpost_set.all %}
            <div class="mySlides overlay-box">
                <img class="portfolio_detail_pic" src="{{ post.image.url }}" style="width:100%">
                <div id="inner-box">
                    <h3 class="w3-center">{{ post.title }}</h3>
                    <p class="w3-center">{{ post.caption }}</p>
                    <figure class="pencil">
                        <a href="{% url 'kidfolio:get_kidpost' post.id %}"><span class="glyphicon glyphicon-pencil" id="pencil"></span></a>
                    </figure>
                </div>
            </div>
    {% endfor %}

    </div>

</div>

<div class="thumbnail-view" id="thumbnail-view">
    <div class="w3-content w3-display-container">

        <div class="thumbnail-grid">
            {% for post in portfolio.kidpicpost_set.all %}
            <a href="{% url 'kidfolio:get_kidpost' post.id %}">
            <img class="thumbnail-pic" src="{{ post.image.url }}">
            </a>
            {% endfor %}
        </div>

    </div>

</div>



# slideshow javascript from w3 schools.

<script>
var slideIndex = 1;
showDivs(slideIndex);

function plusDivs(n) {
  showDivs(slideIndex += n);
}

function showDivs(n) {
  var i;
  var x = document.getElementsByClassName("mySlides");
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length}
  for (i = 0; i < x.length; i++) {
     x[i].style.display = "none";
  }
  x[slideIndex-1].style.display = "block";
}
</script>










{% endblock %}

KidPortfolio/kidfolio/templates/kidfolio/portfolios.html
{% extends "kidfolio/base.html" %}
{% block content %}
{% load front_tags %}



    <div>
        {% for portfolio in user.portfolio_set.all %}
        <a href="{% url 'kidfolio:get_this_portfolio' portfolio.id %}"><h1>{{portfolio.portfolio_name}}</h1></a>

        <div class="grid-box">
            {% for post in portfolio.kidpicpost_set.all reversed %}
            {% if forloop.counter <= 4 %}
                <div class="small_pic_box" id="small_pic_box">

                    <div class="overlay-box">
                        <img class="kidpic pic" src="{{ post.image.url }}"/>

                        <div id="inner-box">

                            <p>{% autoescape off %} {{ post.caption }} {% endautoescape %}</p>
                            <figure class="pencil">
                                <a href="{% url 'kidfolio:get_kidpost' post.id %}"><span class="glyphicon glyphicon-pencil" id="pencil"></span></a>
                            </figure>
                        </div>

                    </div>


                </div>
            {% endif %}
            {% endfor %}
        </div>
        <!--<a href="{% url 'kidfolio:new_kidpost' %}"><button class="make_entry">New KidPost</button></a>-->
        <!--<a href="{% url 'kidfolio:new_portfolio' %}"><button class="make_entry">Make New Portfolio</button></a>-->
        {% endfor %}
    </div>

{% endblock %}

KidPortfolio/kidfolio/templates/kidfolio/thumbnail.html
{% extends "kidfolio/base.html" %}
{% block content%}

        <div class="kidpic_container">
            <h2>{{ form.title }} by {{ form.portfolio }}</h2>
            <div class="art_container">

                    <img class="edit_btn" src="{{ kidpost.image.url }}"/>

            </div>
            <p class="caption">{{ post.caption }}</p>
        </div>


{% endblock %}