intucompass/accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^createuser/$', views.createuser, name='createuser'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^login/$', views.loginpage, name='login'),
    url(r'^loginuser/$', views.loginuser, name='loginuser'),
    url(r'^logout/$', views.logoutuser, name='logout')
]

intucompass/compass/urls.py
from django.conf.urls import url
from . import views

app_name = 'compass'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

intucompass/intucompass/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^compass/', include('compass.urls')),
    url(r'^accounts/', include('accounts.urls')),

]

intucompass/accounts/models.py
from django.db import models

# Create your models here.

intucompass/compass/models.py
from django.db import models
from django.contrib.auth.models import User


# class Thought(models.Model):
#     user = models.ForeignKey(User)
#     text = models.Textfield(max_length=None, blank=False)
#     place = models.Charfield()
#     timestamp = models.DateTimeField(auto_created=True)
#     identifier = models.ForeignKey(Identifiers)
#
# class Identifiers(models.Model):
#     parent = models.
#
#
# class Profile(models.Model):
#     picture =
#     person = models.ForeignKey(User)

intucompass/accounts/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

def register(request):
    return render(request, 'accounts/join.html')

def createuser(request):

    username = request.POST['username']
    email_address = request.POST['email_address']
    password = request.POST['password']

    if User.objects.filter(username=username).exists():
        return render(request, 'accounts/join.html', {'message':'username already exists'})

    user = User.objects.create_user(username=username, email=email_address, password=password)
    login(request, user)
    return render(request, 'accounts/profile.html')


def loginpage(request):
    return render(request, 'accounts/signin.html')

def loginuser(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is None:
        return HttpResponseRedirect(reverse('accounts:login'))
    else:
        login(request, user)
        return HttpResponseRedirect(reverse('accounts:profile'))


# def profile(request):
#     if request.user.is_authenticated:
#         return render(request, 'accounts/profile.html')
#     else:
#         return HttpResponseRedirect(reverse('accounts:register'))


@login_required
def profile(request):
    return render(request, 'accounts/profile.html')


def logoutuser(request):
    logout(request)
    return HttpResponseRedirect(reverse('accounts:login'))

intucompass/compass/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

def index(request):
   return render(request, 'compass/main_map.html')

intucompass/accounts/templates/accounts/join.html
<h1>Join</h1>

{% if message %}
<span style="color:red">{{message}}</span>
{% endif %}


<form action="{% url 'accounts:createuser' %}" method="post" autocomplete="off">
    {% csrf_token %}
    <input type="text" placeholder="username" name="username" required value=""/>
    <input type="text" placeholder="email address" name="email_address" required value=""/>
    <input type="password" placeholder="password" name="password" required value=""/>
    <button type="submit">register</button>
</form>

intucompass/accounts/templates/accounts/profile.html
<h1>Welcome {{request.user.username}}!</h1>

<a href="{% url 'accounts:logout' %}">logout</a>

intucompass/accounts/templates/accounts/signin.html
<h1>Sign In</h1>

<form action="{% url 'accounts:loginuser' %}" method="post" autocomplete="off">
    {% csrf_token %}
    <input type="text" placeholder="username" name="username" required value=""/>
    <input type="password" placeholder="password" name="password" required value=""/>
    <button type="submit">login</button>
</form>

intucompass/compass/templates/compass/landing_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
        <meta name="description" content="">
        <!--<link rel="stylesheet" type="text/css" href="style.css">-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
          /* Always set the map height explicitly to define the size of the div
           * element that contains the map. */
          #map {
              height: 600px;
              width: 600px;


          }
          /* Optional: Makes the sample page fill the window. */

    </style>
    </head>
    <body>
        <header>
            <figure class="main-logo">Intucompass</figure>
            <nav>
                <ul>
                    <li>Thoughts</li>
                    <li>Profile</li>
                    <li>Sign In</li>
                    <li>Join</li>
                </ul>
            </nav>

        </header>
        <main>
            <div class="container">
                <form class="main_loc_search">
                    {% csrf_token %}
                    <input type="text">
                    <button id="search" type="submit">Search</button>
                </form>
            </div>
            <div id="map"></div>
            <script>

              var map, infoWindow;
              function initMap() {
                  $('#search').click(function(e){
                      e.preventDefault();

                      const query = $('#query').val();
                      const pkg = {
                          query: query,
                          key: 'AIzaSyDdvVUAMdAUl5erpzC0vjmcElYdYXfywsw',
                          location: "45.5195739, -122.6128",
                          radius: 1000
                      };
                      $.ajax({
                          url: 'https://maps.googleapis.com/maps/api/place/textsearch/json',
                          data: pkg,
                          dataType: 'json',
                          success: function (data) {

                              for (i = 0; i < data.results.length; i++) {
                                  new_item = document.createElement('li');
                                  anchor = document.createElement('a');
                                  new_item.appendChild(anchor);
                                  ul.appendChild(new_item);
                                  anchor.setAttribute('href', 'link goes here');
//                                  ul.onclick=function() {
//                                      var pos = {
//                                          lat: position.coords.latitude,
//                                          lng: position.coords.longitude
//                                      };
//                                      infoWindow.setPosition()
//                                  };
                                  new_item.classList.add('dropdown');
                                  anchor.innerText = data.results[i].name + data.results[i].formatted_address;
                                  console.log(data.results[i])
                              }
                          }
                      })
                  });



                map = new google.maps.Map(document.getElementById('map'), {
                  center: {lat: -34.397, lng: 150.644},
                  zoom: 10
                });
                infoWindow = new google.maps.InfoWindow;
//                finds location of user IP address.
                if (navigator.geolocation) {
                  navigator.geolocation.getCurrentPosition(function(position) {
                    var pos = {
                      lat: position.coords.latitude,
                      lng: position.coords.longitude
                    };

                    infoWindow.setPosition(pos);
                    infoWindow.setContent('Here you are!');
                    infoWindow.open(map);
                    map.setCenter(pos);

//                    adds marker to found geolocation
                    var marker = new google.maps.Marker({
                      position: pos,
                      map: map,
                      title: 'Hello World!'
                    });

//                   zooms in when the marker is clicked.....

                    marker.addListener('click', function() {
                        map.setZoom(20);
                        map.setCenter(marker.getPosition())
                    });



                    }, function() {
                    handleLocationError(true, infoWindow, map.getCenter());
                  });
                } else {
                  // Browser doesn't support Geolocation
                  handleLocationError(false, infoWindow, map.getCenter());
                }
              }

              function handleLocationError(browserHasGeolocation, infoWindow, pos) {
                infoWindow.setPosition(pos);
                infoWindow.setContent(browserHasGeolocation ?
                                      'Error: The Geolocation service failed.' :
                                      'Error: Your browser doesn\'t support geolocation.');
                infoWindow.open(map);
              }

            </script>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
            <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCG8RCrC_9q0rXFQM334O78Pz_pFPsWL7E&callback=initMap"></script>

        </main>



    </body>
</html>

intucompass/compass/templates/compass/main_map.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title></title>
        <meta name="description" content="">
        <!--<link rel="stylesheet" type="text/css" href="style.css">-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            body {
                font-family: Helvetica, Arial;
            }

            .query {
                width: 25%;
                margin-bottom: 5px;
                padding: 5px;
                font-size: 16px;
            }

            .search {
                padding: 8px 20px;
                font-size: 16px;
                background-color: rgba(57, 172, 115, .8);
                color: #fff;
                position: absolute;
                z-index: 1;
            }

            .search:hover {
                padding: 14px 26px;
                background-color: rgba(140, 217, 177, .6)

            }

            .map_area {
                margin: auto;
                width: 80%;


            }
            .google_map {
               height: 600px;
               width: 100%;
               margin: auto;

            }
            .drop_list_box {
                box-sizing: border-box;
                background-color: rgba(255,255,255,.5);
                position: absolute;
                display: none;
                overflow: auto;
                z-index: 1;


                }
            .drop_list {
              list-style-type: none;
              margin: 0;
              padding: 0;
            }

            .dropdown {

              font-size: 14px;
              margin-top: 2px;
              width: 100%;
              padding: 6px;
              border: none;
              text-align: left;
              background-color: rgba(255,255,255,.3);

            }

            .dropdown:hover {
              background-color: rgba(57, 172, 115, .5)

            }

            a:hover {
                color: rgb(255,255,255);
            }

            .show {
                display:block;
            }

            a {
                text-decoration: none;
                font-size: 16px;
                color: rgba(57, 172, 115, .8)
            }
        </style>
    </head>
    <body>

        <header>
            <figure class="med-logo">Intucompass</figure>
            <nav>
                <ul>
                    <li>Thoughts</li>
                    <li>Profile</li>
                    <li>Sign In</li>
                    <li>Join</li>
                </ul>
            </nav>

            <input id="query" class="query" type="text">
            <button id="search" class="search" type="submit">Find it!</button>
            <div id='drop_list' class="drop_list_box">
              <ul id='ul' class='drop_list'></ul>
            </div>
            <script>


            </script>

        </header>

        <main>


            <div class="map_area">
                <figure class="google_map" id="map">
                    <script>
                      function initMap() {
                        var pdx = {lat: 45.52306220000001, lng: -122.6764815};
                        var map = new google.maps.Map(document.getElementById('map'), {
                          zoom: 10,
                          center: pdx,
                        });

                        infoWindow = new google.maps.InfoWindow;
//                finds location of user IP address.
                        if (navigator.geolocation) {
                            navigator.geolocation.getCurrentPosition(function(position) {
                            var pos = {
                                lat: position.coords.latitude,
                                lng: position.coords.longitude
                            };

                            infoWindow.setPosition(pos);
                            infoWindow.setContent('Here you are!');
                            infoWindow.open(map);
                            map.setCenter(pos);

//                    adds marker to found geolocation
                        var marker = new google.maps.Marker({
                            position: pos,
                            map: map,
                            title: 'Hello World!'
                        });

//                   zooms in when the marker is clicked.....

                        marker.addListener('click', function() {
                            map.setZoom(20);
                            map.setCenter(marker.getPosition())
                        });

                        }, function() {
                                handleLocationError(true, infoWindow, map.getCenter());
                            });
                        } else {
                  // Browser doesn't support Geolocation
                                handleLocationError(false, infoWindow, map.getCenter());
                        }
                     }

                    function handleLocationError(browserHasGeolocation, infoWindow, pos) {
                        infoWindow.setPosition(pos);
                        infoWindow.setContent(browserHasGeolocation ?
                                      'Error: The Geolocation service failed.' :
                                      'Error: Your browser doesn\'t support geolocation.');
                        infoWindow.open(map);
                    }


                    </script>
                </figure>

            </div>

            <aside class="thought_feed">
                <div class="bubble one"></div>
                <div class="bubble two"></div>
                <div class="bubble three"></div>
                <div class="bubble four"></div>

            </aside>
        </main>
        <!--<script src="apikey.js"></script>-->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCG8RCrC_9q0rXFQM334O78Pz_pFPsWL7E&callback=initMap">
    </script>
    <script>

                window.onclick = function(event) {
                    if (!event.target.matches('#search')) {
                        var dropdown = document.getElementById('drop_list');
                        dropdown.classList.remove('show');
                    }
                };



        $('#search').click(function(e){
            e.preventDefault();

            document.getElementById("drop_list").classList.add("show");
            ul = document.getElementById('ul');

            while (ul.firstChild) {
                ul.removeChild(ul.firstChild);
            }

            const query = $('#query').val();
            const pkg = {
                query: query,
                key: 'AIzaSyDdvVUAMdAUl5erpzC0vjmcElYdYXfywsw',
                location: "45.5195739, -122.6128",
                radius: 1000
            };

            $.ajax({
                url: 'https://maps.googleapis.com/maps/api/place/textsearch/json',
                data: pkg,
                dataType: 'json',
                success: function(data){

                    for (i=0; i<data.results.length; i++) {
                        new_item = document.createElement('li');
                        anchor = document.createElement('a');
                        new_item.appendChild(anchor);
                        ul.appendChild(new_item);
                        anchor.setAttribute('href', 'link goes here');
                        new_item.classList.add('dropdown');
                        anchor.innerText = data.results[i].name + data.results[i].formatted_address;
                        console.log(data.results[i])
                    }

//                    console.log(data)
                }
            })

        });
    </script>

    </body>
</html>